onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /SYS_TB/i
add wave -noupdate /SYS_TB/Width
add wave -noupdate /SYS_TB/UART_CLK_tb
add wave -noupdate /SYS_TB/REF_CLK_tb
add wave -noupdate /SYS_TB/Rx_IN_tb
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/RX_P_Data
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/RX_D_VLD
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/Addr
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/WrEn
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/Wr_D
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/Rd_D
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/RdEn
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/Rd_D_VLD
add wave -noupdate {/SYS_TB/DUT/U0_Register_File/Mem[10]}
add wave -noupdate /SYS_TB/DUT/U0_Register_File/REG0
add wave -noupdate /SYS_TB/DUT/U0_Register_File/REG1
add wave -noupdate /SYS_TB/Tx_out_tb
add wave -noupdate /SYS_TB/Reset_tb
add wave -noupdate /SYS_TB/Depth
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/clk_div_en
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/busy
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/Width
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/RST
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/OUT_VLD
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/Depth
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/CLK_EN
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/CLK
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/ALU_OUT
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/ALU_FUN
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/ALU_EN
add wave -noupdate /SYS_TB/DUT/U0_Register_File/RdData_VLD
add wave -noupdate /SYS_TB/DUT/U0_Register_File/RdData
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/enable_pulse_d
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/enable_pulse
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/enable_flop
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/bus_enable
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/Width
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/Sync_flop
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/Sync_Data_out
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/Sync_Data
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/RST
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/P_Data_in
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/Meta_flop
add wave -noupdate /SYS_TB/DUT/U1_uart_Data_Sync/CLK
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/TX_P_Data_c
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/TX_P_Data
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/TX_D_VLD_c
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/TX_D_VLD
add wave -noupdate /SYS_TB/DUT/U0_ALU/ALU_OUT_comb
add wave -noupdate /SYS_TB/DUT/U0_ALU/CLK
add wave -noupdate /SYS_TB/DUT/U0_ALU/OUT_VALID_comb
add wave -noupdate /SYS_TB/DUT/U0_ALU/OUT_VALID
add wave -noupdate /SYS_TB/DUT/U0_ALU/EN
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/busy
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/ALU_OUT_Reg
add wave -noupdate /SYS_TB/DUT/U0_SYS_CTRL/U_SYS_TX_FSM/current_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {82304 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {81772 ps} {82772 ps}
